on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be built and deployed'
        required: true

name: Manual build and publish to ECR
jobs:
  manual-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Set environment by tag suffix
        id: set_env_by_tag
        # Available at ${{ steps.set_env_by_tag.outputs.ENV }}
        run: |
          echo ${{ github.event.inputs.tag }}
          if [[ ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-pre.[0-9]+$ ]]; then
            echo ::set-output name=ENV::qa
          elif [[ ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-staging.[0-9]+$ ]]; then
            echo ::set-output name=ENV::staging
          elif [[ ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=ENV::prod
          else
            echo ::set-output name=ENV::unknown
          fi

      - name: Echo environment variable
        run: echo ${{ steps.set_env_by_tag.outputs.ENV }}
